[package]
name = "train"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = "4.1.8"
flate2 = "1.0.25"
indextree = "4.6.0"
rand = "0.8.5"
regex = "1.7.1"
tar = "0.4.38"
